FROM node:16-alpine as build-stage

COPY . /home/dev/capsule-vue

WORKDIR /home/dev/capsule-vue

RUN time tar -xf node_modules.tar.gz
RUN time yarn build:web

FROM nginx:1.15

COPY --from=build-stage /home/dev/capsule-vue/.docker_files/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /home/dev/capsule-vue/.app /var/www/capsule-vue
