export const feelings = {
	positive: [
		`face1`,
		`face5`,
		`face13`,
		`face14`,
		`face15`,
		`face18`,
		`face19`,
		`face23`,
		`face24`,
		`face25`,
		`face26`,
		`face28`,
		`face35`,
		`face36`,
		`face37`,
		`face44`,
		`face45`,
		`face46`,
		`face47`,
		`face48`,
		`face49`,
	],
	negative: [
		`face2`,
		`face3`,
		`face4`,
		`face8`,
		`face9`,
		`face10`,
		`face11`,
		`face12`,
		`face16`,
		`face29`,
		`face30`,
		`face32`,
		`face33`,
		`face38`,
		`face43`,
	],
	neutral: [
		`face6`,
		`face7`,
		`face17`,
		`face20`,
		`face21`,
		`face22`,
		`face27`,
		`face31`,
		`face34`,
		`face39`,
		`face40`,
		`face41`,
		`face42`,
		`face51`,
		`face52`,
	],
}

export const avatars = [
	require(`@/assets/images/avatars/beats.jpeg`),
	require(`@/assets/images/avatars/cassete.jpeg`),
	require(`@/assets/images/avatars/footballhead.jpeg`),
	require(`@/assets/images/avatars/hiphopblood.jpeg`),
	require(`@/assets/images/avatars/hiphopcribs.jpeg`),
	require(`@/assets/images/avatars/hiphopking.jpeg`),
	require(`@/assets/images/avatars/meathead.jpeg`),
	require(`@/assets/images/avatars/blues.jpeg`),
	require(`@/assets/images/avatars/fastfood.jpeg`),
	require(`@/assets/images/avatars/streetart.jpeg`),
	require(`@/assets/images/avatars/strongwomen.jpeg`),
]

export const reactions = {
	face1: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face1.png`),
		imageRight: require(`@/assets/images/reactions/right/face1.png`),
	},
	face2: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face2.png`),
		imageRight: require(`@/assets/images/reactions/right/face2.png`),
	},
	face3: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face3.png`),
		imageRight: require(`@/assets/images/reactions/right/face3.png`),
	},
	face4: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face4.png`),
		imageRight: require(`@/assets/images/reactions/right/face4.png`),
	},
	face5: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face5.png`),
		imageRight: require(`@/assets/images/reactions/right/face5.png`),
	},
	face6: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face6.png`),
		imageRight: require(`@/assets/images/reactions/right/face6.png`),
	},
	face7: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face7.png`),
		imageRight: require(`@/assets/images/reactions/right/face7.png`),
	},
	face8: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face8.png`),
		imageRight: require(`@/assets/images/reactions/right/face8.png`),
	},
	face9: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face9.png`),
		imageRight: require(`@/assets/images/reactions/right/face9.png`),
	},
	face10: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face10.png`),
		imageRight: require(`@/assets/images/reactions/right/face10.png`),
	},
	face11: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face11.png`),
		imageRight: require(`@/assets/images/reactions/right/face11.png`),
	},
	face12: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face12.png`),
		imageRight: require(`@/assets/images/reactions/right/face12.png`),
	},
	face13: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face13.png`),
		imageRight: require(`@/assets/images/reactions/right/face13.png`),
	},
	face14: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face14.png`),
		imageRight: require(`@/assets/images/reactions/right/face14.png`),
	},
	face15: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face15.png`),
		imageRight: require(`@/assets/images/reactions/right/face15.png`),
	},
	face16: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face16.png`),
		imageRight: require(`@/assets/images/reactions/right/face16.png`),
	},
	face17: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face17.png`),
		imageRight: require(`@/assets/images/reactions/right/face17.png`),
	},
	face18: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face18.png`),
		imageRight: require(`@/assets/images/reactions/right/face18.png`),
	},
	face19: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face19.png`),
		imageRight: require(`@/assets/images/reactions/right/face19.png`),
	},
	face20: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face20.png`),
		imageRight: require(`@/assets/images/reactions/right/face20.png`),
	},
	face21: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face21.png`),
		imageRight: require(`@/assets/images/reactions/right/face21.png`),
	},
	face22: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face22.png`),
		imageRight: require(`@/assets/images/reactions/right/face22.png`),
	},
	face23: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face23.png`),
		imageRight: require(`@/assets/images/reactions/right/face23.png`),
	},
	face24: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face24.png`),
		imageRight: require(`@/assets/images/reactions/right/face24.png`),
	},
	face25: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face25.png`),
		imageRight: require(`@/assets/images/reactions/right/face25.png`),
	},
	face26: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face26.png`),
		imageRight: require(`@/assets/images/reactions/right/face26.png`),
	},
	face27: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face27.png`),
		imageRight: require(`@/assets/images/reactions/right/face27.png`),
	},
	face28: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face28.png`),
		imageRight: require(`@/assets/images/reactions/right/face28.png`),
	},
	face29: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face29.png`),
		imageRight: require(`@/assets/images/reactions/right/face29.png`),
	},
	face30: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face30.png`),
		imageRight: require(`@/assets/images/reactions/right/face30.png`),
	},
	face31: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face31.png`),
		imageRight: require(`@/assets/images/reactions/right/face31.png`),
	},
	face32: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face32.png`),
		imageRight: require(`@/assets/images/reactions/right/face32.png`),
	},
	face33: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face33.png`),
		imageRight: require(`@/assets/images/reactions/right/face33.png`),
	},
	face34: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face34.png`),
		imageRight: require(`@/assets/images/reactions/right/face34.png`),
	},
	face35: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face35.png`),
		imageRight: require(`@/assets/images/reactions/right/face35.png`),
	},
	face36: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face36.png`),
		imageRight: require(`@/assets/images/reactions/right/face36.png`),
	},
	face37: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face37.png`),
		imageRight: require(`@/assets/images/reactions/right/face37.png`),
	},
	face38: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face38.png`),
		imageRight: require(`@/assets/images/reactions/right/face38.png`),
	},
	face39: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face39.png`),
		imageRight: require(`@/assets/images/reactions/right/face39.png`),
	},
	face40: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face40.png`),
		imageRight: require(`@/assets/images/reactions/right/face40.png`),
	},
	face41: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face41.png`),
		imageRight: require(`@/assets/images/reactions/right/face41.png`),
	},
	face42: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face42.png`),
		imageRight: require(`@/assets/images/reactions/right/face42.png`),
	},
	face43: {
		filter: `negative`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face43.png`),
		imageRight: require(`@/assets/images/reactions/right/face43.png`),
	},
	face44: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face44.png`),
		imageRight: require(`@/assets/images/reactions/right/face44.png`),
	},
	face45: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face45.png`),
		imageRight: require(`@/assets/images/reactions/right/face45.png`),
	},
	face46: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face46.png`),
		imageRight: require(`@/assets/images/reactions/right/face46.png`),
	},
	face47: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face47.png`),
		imageRight: require(`@/assets/images/reactions/right/face47.png`),
	},
	face48: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face48.png`),
		imageRight: require(`@/assets/images/reactions/right/face48.png`),
	},
	face49: {
		filter: `positive`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face49.png`),
		imageRight: require(`@/assets/images/reactions/right/face49.png`),
	},
	face50: {
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face50.png`),
		imageRight: require(`@/assets/images/reactions/right/face50.png`),
	},
	face51: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face51.png`),
		imageRight: require(`@/assets/images/reactions/right/face51.png`),
	},
	face52: {
		filter: `neutral`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/left/face52.png`),
		imageRight: require(`@/assets/images/reactions/right/face52.png`),
	},
	default: {
		filter: `white`,
		label: ``,
		imageLeft: require(`@/assets/images/reactions/default.png`),
		imageRight: require(`@/assets/images/reactions/default.png`),
	},
}

export const categories = [
	`technology`,
	`crypto`,
	`politics`,
	`US-world`,
	`science`,
	`environment`,
	`food-drink`,
	`culture`,
	`education`,
	`philosophy`,
	`news`,
	`sports`,
]

export const backgrounds = {
	positive: require(`@/assets/images/backgrounds/agree.webp`),
	negative: require(`@/assets/images/backgrounds/disagree.webp`),
	neutral: require(`@/assets/images/backgrounds/neutral.webp`),
	default: require(`@/assets/images/backgrounds/paper.webp`),
}
