export const faces = {
	default: {
		label: `default`,
		leftImage: require(`@/assets/images/reactions/default.png`),
		rightImage: require(`@/assets/images/reactions/default.png`),
	},
	admiration: {
		label: `admiration`,
		leftImage: require(`@/assets/images/reactions/left-side/admiration.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/admiration.webp`),
	},
	aloof: {
		label: `aloof`,
		leftImage: require(`@/assets/images/reactions/left-side/aloof.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/aloof.webp`),
	},
	awe: {
		label: `awe`,
		leftImage: require(`@/assets/images/reactions/left-side/awe.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/awe.webp`),
	},
	bored: {
		label: `bored`,
		leftImage: require(`@/assets/images/reactions/left-side/bored.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/bored.webp`),
	},
	brave: {
		label: `brave`,
		leftImage: require(`@/assets/images/reactions/left-side/brave.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/brave.webp`),
	},
	calm: {
		label: `calm`,
		leftImage: require(`@/assets/images/reactions/left-side/calm.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/calm.webp`),
	},
	committed: {
		label: `committed`,
		leftImage: require(`@/assets/images/reactions/left-side/committed.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/committed.webp`),
	},
	confident: {
		label: `confident`,
		leftImage: require(`@/assets/images/reactions/left-side/confident.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/confident.webp`),
	},
	cringe: {
		label: `cringe`,
		leftImage: require(`@/assets/images/reactions/left-side/cringe.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/cringe.webp`),
	},
	curious: {
		label: `curious`,
		leftImage: require(`@/assets/images/reactions/left-side/curious.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/curious.webp`),
	},
	defiant: {
		label: `defiant`,
		leftImage: require(`@/assets/images/reactions/left-side/defiant.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/defiant.webp`),
	},
	detatched: {
		label: `detatched`,
		leftImage: require(`@/assets/images/reactions/left-side/detatched.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/detatched.webp`),
	},
	determined: {
		label: `determined`,
		leftImage: require(`@/assets/images/reactions/left-side/determined.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/determined.webp`),
	},
	disgusted: {
		label: `disgusted`,
		leftImage: require(`@/assets/images/reactions/left-side/disgusted.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/disgusted.webp`),
	},
	distracted: {
		label: `distracted`,
		leftImage: require(`@/assets/images/reactions/left-side/distracted.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/distracted.webp`),
	},
	empathy: {
		label: `empathy`,
		leftImage: require(`@/assets/images/reactions/left-side/empathy.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/empathy.webp`),
	},
	enlighten: {
		label: `enlighten`,
		leftImage: require(`@/assets/images/reactions/left-side/enlighten.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/enlighten.webp`),
	},
	enthusiastic: {
		label: `enthusiastic`,
		leftImage: require(`@/assets/images/reactions/left-side/enthusiastic.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/enthusiastic.webp`),
	},
	excited: {
		label: `excited`,
		leftImage: require(`@/assets/images/reactions/left-side/excited.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/excited.webp`),
	},
	fearful: {
		label: `fearful`,
		leftImage: require(`@/assets/images/reactions/left-side/fearful.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/fearful.webp`),
	},
	fearless: {
		label: `fearless`,
		leftImage: require(`@/assets/images/reactions/left-side/fearless.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/fearless.webp`),
	},
	friendly: {
		label: `friendly`,
		leftImage: require(`@/assets/images/reactions/left-side/friendly.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/friendly.webp`),
	},
	fulfilled: {
		label: `fulfilled`,
		leftImage: require(`@/assets/images/reactions/left-side/fulfilled.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/fulfilled.webp`),
	},
	furious: {
		label: `furious`,
		leftImage: require(`@/assets/images/reactions/left-side/furious.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/furious.webp`),
	},
	glad: {
		label: `glad`,
		leftImage: require(`@/assets/images/reactions/left-side/glad.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/glad.webp`),
	},
	guffaw: {
		label: `guffaw`,
		leftImage: require(`@/assets/images/reactions/left-side/guffaw.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/guffaw.webp`),
	},
	happy: {
		label: `happy`,
		leftImage: require(`@/assets/images/reactions/left-side/happy.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/happy.webp`),
	},
	hateful: {
		label: `hateful`,
		leftImage: require(`@/assets/images/reactions/left-side/hateful.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/hateful.webp`),
	},
	heartbroken: {
		label: `heartbroken`,
		leftImage: require(`@/assets/images/reactions/left-side/heartbroken.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/heartbroken.webp`),
	},
	hesitant: {
		label: `hesitant`,
		leftImage: require(`@/assets/images/reactions/left-side/hesitant.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/hesitant.webp`),
	},
	hostile: {
		label: `hostile`,
		leftImage: require(`@/assets/images/reactions/left-side/hostile.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/hostile.webp`),
	},
	hush: {
		label: `hush`,
		leftImage: require(`@/assets/images/reactions/left-side/hush.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/hush.webp`),
	},
	incognito: {
		label: `incognito`,
		leftImage: require(`@/assets/images/reactions/left-side/incognito.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/incognito.webp`),
	},
	incredulous: {
		label: `incredulous`,
		leftImage: require(`@/assets/images/reactions/left-side/incredulous.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/incredulous.webp`),
	},
	indifferent: {
		label: `indifferent`,
		leftImage: require(`@/assets/images/reactions/left-side/indifferent.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/indifferent.webp`),
	},
	informed: {
		label: `informed`,
		leftImage: require(`@/assets/images/reactions/left-side/informed.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/informed.webp`),
	},
	interested: {
		label: `interested`,
		leftImage: require(`@/assets/images/reactions/left-side/interested.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/interested.webp`),
	},
	intrigued: {
		label: `intrigued`,
		leftImage: require(`@/assets/images/reactions/left-side/intrigued.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/intrigued.webp`),
	},
	lol: {
		label: `lol`,
		leftImage: require(`@/assets/images/reactions/left-side/lol.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/lol.webp`),
	},
	lovely: {
		label: `lovely`,
		leftImage: require(`@/assets/images/reactions/left-side/lovely.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/lovely.webp`),
	},
	mad: {
		label: `mad`,
		leftImage: require(`@/assets/images/reactions/left-side/mad.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/mad.webp`),
	},
	offended: {
		label: `offended`,
		leftImage: require(`@/assets/images/reactions/left-side/offended.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/offended.webp`),
	},
	on_it: {
		label: `on_it`,
		leftImage: require(`@/assets/images/reactions/left-side/on_it.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/on_it.webp`),
	},
	proud: {
		label: `proud`,
		leftImage: require(`@/assets/images/reactions/left-side/proud.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/proud.webp`),
	},
	regret: {
		label: `regret`,
		leftImage: require(`@/assets/images/reactions/left-side/regret.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/regret.webp`),
	},
	revolted: {
		label: `revolted`,
		leftImage: require(`@/assets/images/reactions/left-side/revolted.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/revolted.webp`),
	},
	sad: {
		label: `sad`,
		leftImage: require(`@/assets/images/reactions/left-side/sad.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/sad.webp`),
	},
	satisfied: {
		label: `satisfied`,
		leftImage: require(`@/assets/images/reactions/left-side/satisfied.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/satisfied.webp`),
	},
	shocked: {
		label: `shocked`,
		leftImage: require(`@/assets/images/reactions/left-side/shocked.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/shocked.webp`),
	},
	sick: {
		label: `sick`,
		leftImage: require(`@/assets/images/reactions/left-side/sick.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/sick.webp`),
	},
	skeptical: {
		label: `skeptical`,
		leftImage: require(`@/assets/images/reactions/left-side/skeptical.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/skeptical.webp`),
	},
	spiritless: {
		label: `spiritless`,
		leftImage: require(`@/assets/images/reactions/left-side/spiritless.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/spiritless.webp`),
	},
	spunky: {
		label: `spunky`,
		leftImage: require(`@/assets/images/reactions/left-side/spunky.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/spunky.webp`),
	},
	suspicious: {
		label: `suspicious`,
		leftImage: require(`@/assets/images/reactions/left-side/suspicious.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/suspicious.webp`),
	},
	terrified: {
		label: `terrified`,
		leftImage: require(`@/assets/images/reactions/left-side/terrified.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/terrified.webp`),
	},
	triggered: {
		label: `triggered`,
		leftImage: require(`@/assets/images/reactions/left-side/triggered.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/triggered.webp`),
	},
	trippy: {
		label: `trippy`,
		leftImage: require(`@/assets/images/reactions/left-side/trippy.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/trippy.webp`),
	},
	violent: {
		label: `violent`,
		leftImage: require(`@/assets/images/reactions/left-side/violent.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/violent.webp`),
	},
	whine: {
		label: `whine`,
		leftImage: require(`@/assets/images/reactions/left-side/whine.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/whine.webp`),
	},
	wild: {
		label: `wild`,
		leftImage: require(`@/assets/images/reactions/left-side/wild.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/wild.webp`),
	},
	zzz: {
		label: `zzz`,
		leftImage: require(`@/assets/images/reactions/left-side/zzz.webp`),
		rightImage: require(`@/assets/images/reactions/right-side/zzz.webp`),
	},
}

export const faceGroupings = [
	// Positive
	[faces.curious, faces.informed, faces.enlighten],
	[faces.glad, faces.happy, faces.excited],
	[faces.confident, faces.brave, faces.fearless],
	[faces.defiant, faces.determined, faces.on_it],
	[faces.enthusiastic, faces.lol, faces.guffaw],
	[faces.intrigued, faces.interested, faces.committed],
	[faces.proud, faces.admiration, faces.awe],
	// Neutral
	[faces.empathy, faces.friendly, faces.lovely],
	[faces.calm, faces.satisfied, faces.fulfilled],
	[faces.mad, faces.hostile, faces.violent],
	[faces.hush, faces.wild, faces.zzz],
	[faces.regret, faces.spunky, faces.trippy],

	// Negative
	[faces.distracted, faces.bored, faces.spiritless],
	[faces.cringe, faces.offended, faces.hateful],
	[faces.triggered, faces.shocked, faces.furious],
	[faces.disgusted, faces.sick, faces.revolted],
	[faces.suspicious, faces.incredulous, faces.skeptical],
	[faces.hesitant, faces.fearful, faces.terrified],
	[faces.aloof, faces.indifferent, faces.detatched],
	[faces.sad, faces.whine, faces.heartbroken],
]

export const feelings = {
	positive: [
		`curious`,
		`informed`,
		`enlighten`,
		`glad`,
		`happy`,
		`excited`,
		`confident`,
		`brave`,
		`fearless`,
		`enthusiastic`,
		`lol`,
		`guffaw`,
		`intrigued`,
		`interested`,
		`committed`,
		`proud`,
		`admiration`,
		`awe`,
	],
	negative: [
		`distracted`,
		`bored`,
		`spiritless`,
		`triggered`,
		`shocked`,
		`furious`,
		`disgusted`,
		`sick`,
		`revolted`,
		`suspicious`,
		`incredulous`,
		`skeptical`,
		`hesitant`,
		`fearful`,
		`terrified`,
		`aloof`,
		`indifferent`,
		`detatched`,
		`sad`,
		`whine`,
		`heartbroken`,
		`cringe`,
		`offended`,
		`hateful`,
	],
	neutral: [
		`empathy`,
		`friendly`,
		`lovely`,
		`calm`,
		`satisfied`,
		`fulfilled`,
		`mad`,
		`hostile`,
		`violent`,
		`hush`,
		`wild`,
		`zzz`,
		`regret`,
		`spunky`,
		`trippy`,
	],
}

export const avatars = [
	require(`@/assets/images/avatars/beats.jpeg`),
	require(`@/assets/images/avatars/cassete.jpeg`),
	require(`@/assets/images/avatars/footballhead.jpeg`),
	require(`@/assets/images/avatars/hiphopblood.jpeg`),
	require(`@/assets/images/avatars/hiphopcribs.jpeg`),
	require(`@/assets/images/avatars/hiphopking.jpeg`),
	require(`@/assets/images/avatars/meathead.jpeg`),
	require(`@/assets/images/avatars/blues.jpeg`),
	require(`@/assets/images/avatars/fastfood.jpeg`),
	require(`@/assets/images/avatars/streetart.jpeg`),
	require(`@/assets/images/avatars/strongwomen.jpeg`),
]

export const categories = [
	`technology`,
	`crypto`,
	`politics`,
	`US-world`,
	`science`,
	`environment`,
	`food-drink`,
	`culture`,
	`education`,
	`philosophy`,
	`news`,
	`sports`,
]

export const backgrounds = {
	positive: require(`@/assets/images/backgrounds/agree.webp`),
	negative: require(`@/assets/images/backgrounds/disagree.webp`),
	neutral: require(`@/assets/images/backgrounds/neutral.webp`),
	default: require(`@/assets/images/backgrounds/paper.webp`),
}
