name: Capsule Vue -- Validate Branch
on:
  push:
    branches:
      - '**'
env:
  GITHUB_USER: dgrisham
  GITHUB_TOKEN: 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

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - uses: actions/checkout@v1

      - name: install git
        run: apk add --no-cache git

      - name: yarn install
        run: yarn install

      # this copy of node_modules will be used for the rest of the workflow
      - name: compress node_modules
        run: tar -czf node_modules.tar.gz node_modules
      - uses: actions/upload-artifact@v2
        with:
          name: node_modules.tar.gz
          path: node_modules.tar.gz

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: node_modules.tar.gz
      - name: extract node_modules
        run: tar -xzf node_modules.tar.gz

      - name: lint
        run: yarn lint

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: node_modules.tar.gz
      - name: extract node_modules
        run: tar -xzf node_modules.tar.gz

      - name: build
        run: yarn build:web
