name: Capsule Vue -- Cure53 Deploy
on:
  push:
    tags:
      - cure53
env:
  GITHUB_USER: dgrisham
  GITHUB_TOKEN: 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
  DEPLOY_ENV: cure53

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - uses: actions/checkout@v1

      - name: install tar (for actions/cache)
        run: apk add --no-cache tar

      # use the cached node_modules -- this is only used to speed up the install-dependencies job
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install git
        run: apk add --no-cache git

      - name: yarn install
        run: yarn install

      # this copy of node_modules will be used for the rest of the workflow
      - name: compress node_modules
        run: tar -czf node_modules.tar.gz node_modules
      - uses: actions/upload-artifact@v2
        with:
          name: node_modules.tar.gz
          path: node_modules.tar.gz

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: node_modules.tar.gz
      - name: extract node_modules
        run: tar -xzf node_modules.tar.gz

      - name: lint
        run: yarn lint

  release:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:

      - name: install git
        run: apk add --no-cache git

      - name: workaround for git directory permission issue, see https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory /__w/capsule-vue/capsule-vue

      - uses: actions/checkout@v1

      - name: Setup .env
        run: |
          cat <<EOF >.env
            CONTRACT_NAME="dev-1635323648697-81373157539648"
            DOMAIN="https://cure53.blogchain.app"
            CAPSULE_SERVER="https://cure53.blogchain.app/server"
            ORBIT_URL="https://cure53.blogchain.app/orbit"
            TORUS_GOOGLE_VERIFIER="capsule-social-google-chris"
            TORUS_GOOGLE_CLIENTID="653379121360-j8t9ua763vfvd86d1qjguonhrgqvkigo.apps.googleusercontent.com"
            TORUS_DISCORD_VERIFIER="capsule-social-test-v2-discord"
            TORUS_DISCORD_CLIENTID="906210984396468275"
          EOF

      - name: Set deploy environment vars
        run: echo "RELEASE_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        with:
          name: node_modules.tar.gz
      - name: extract node_modules
        run: tar -xzf node_modules.tar.gz

      - name: build
        run: yarn build:web

      - name: Compress capsule-vue static site
        run: |
          [[ -d .app ]] || { echo "Missing .app, exiting" >&2 ; exit 1 ; }
          build_name="capsule_vue-$DEPLOY_ENV-$RELEASE_ID"
          mv .app $build_name
          tar -czvf "${build_name}.tar.gz" "$build_name"
          echo "BUILD_NAME=$build_name" >> $GITHUB_ENV
        env:
          DEPLOY_ENV: ${{ env.DEPLOY_ENV }}
          RELEASE_ID: ${{ env.RELEASE_ID }}

      - name: Upload build as release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts:    ${{ env.BUILD_NAME }}.tar.gz
          token:        ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

  deploy:
    needs: release
    runs-on: ubuntu-latest
    container:
      image: lexauw/ansible-alpine:latest
    steps:

      - name: install git
        run: apk add --no-cache git

      - name: workaround for git directory permission issue, see https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory /__w/capsule-vue/capsule-vue

      - uses: actions/checkout@v1

      - name: install bash
        run: apk add --no-cache bash

      - name: Set deploy environment vars
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}"     >> $GITHUB_ENV
          echo "RELEASE_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Deploy updated images
        run: ./.github/scripts/deploy.sh
        env:
          DEPLOY_ENV:          ${{ env.DEPLOY_ENV }}
          RELEASE_ID:          ${{ env.RELEASE_ID }}
          RELEASE_TAG:         ${{ env.RELEASE_TAG }}
          GITHUB_USER:         ${{ env.GITHUB_USER }}
          GITHUB_TOKEN:        ${{ env.GITHUB_TOKEN }}
          ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
